-- Esquema inicial de la base de datos (Supabase / Postgres).
--
-- Aquí definiremos las tablas del dominio cuando arranquemos la fase de datos.
-- Por ahora queda como guía de lo que necesitamos modelar:
--
--   pensums       -> un plan académico por carrera y versión (ej. "Contaduría 2024-1").
--   asignaturas   -> las materias de cada pensum (nombre, código, créditos, intensidad, semestre).
--   casos         -> cada solicitud de homologación de un estudiante (institución origen,
--                    carrera destino, estado, fecha, confianza promedio de la IA).
--   vinculos      -> las relaciones origen<->destino sugeridas por Groq para un caso,
--                    con su porcentaje de similitud y su estado (pendiente/aprobado/rechazado).
--
-- Cuando definamos las columnas exactas, este archivo se convierte en la primera
-- migración real que corre el CLI de Supabase.
